name: Level CI Accessibility Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Level CI Accessibility Analysis
        uses: UserWayOrg/cicd-action@dev
        env:
          LEVEL_CI_TOKEN: ${{ secrets.LEVEL_CI_TOKEN }}
          LEVEL_CI_USERNAME: ${{ secrets.LEVEL_CI_USERNAME }}
          LEVEL_CI_PASSWORD: ${{ secrets.LEVEL_CI_PASSWORD }}
