name: Level CI Accessibility Analysis

on: [push, pull_request]

jobs:
  accessibility-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: level-ci.config.ts
          sparse-checkout-cone-mode: false

      - name: Level CI Accessibility Analysis
        uses: UserWayOrg/cicd-action@dev
        env:
          LEVEL_CI_TOKEN: ${{ secrets.LEVEL_CI_TOKEN }}
          LEVEL_CI_USERNAME: ${{ secrets.LEVEL_CI_USERNAME }}
          LEVEL_CI_PASSWORD: ${{ secrets.LEVEL_CI_PASSWORD }}
